### ISSUE TITLE
TLS Automation

### ISSUE THREAD

**Issue by pcho** [ergochat/ergo#1879]
I know there was this #125 and we can use reverse proxy or certbot automation, but it would be nice to have fully automated TLS handling by using https://github.com/caddyserver/certmagic. 

Simplifying user configuration to just:

```yaml
":6697":
    tls: true
    proxy: false
    min-tls-version: 1.2
```

Is this a possibility? :)
