### ISSUE TITLE
Huge amount of zombie ssl_client processes

### ISSUE THREAD

**Issue by p4block** [ergochat/ergo#2096]
As per title. We're using PROXY protocol for our IRC behind a cloud LB.

![image](https://github.com/ergochat/ergo/assets/5960575/c7b8daea-ab6a-4c82-916b-045dc05c2ed9)

Config (snippet):
```
network:
    name: ourdomain.com

server:
    # server name
    name: ourdomain.com


    listeners:
        ":6667": # (loopback ipv4, localhost-only)
            proxy: true

        # The standard SSL/TLS port for IRC is 6697. This will listen on all interfaces:
        ":6697":
            tls:
                cert: "/data/fullchain.pem"
                key: "/data/privkey.pem"
            proxy: true
            min-tls-version: 1.2

      proxy-allowed-from:
         - 167.233.22.11



[...]
    auth-script:
        enabled: true
        command: "/ircd/auth.sh"
        args: ["https://user.ourdomain.com/irc/ergochat/login"]
        autocreate: true
        timeout: 9s
        kill-timeout: 1s
        max-concurrency: 64
```

I'm suspecting it's related to the auth script. 

```
#!/bin/sh
read input
wget --header='CONTENT-TYPE:application/json' --post-data "$input" -O - -q $1 && printf '\n' # This assume no endline ohne the API response
```

[Related issue](https://github.com/orgs/portainer/discussions/10314#discussioncomment-7009006) may be with wget in alpine
